name: Deploy to WordPress.org
on:
    push:
        tags:
            - '*'
jobs:
    tag:
        name: New tag
        runs-on: ubuntu-latest
        steps:
            - name: Clone
              uses: actions/checkout@v2
            - name: Build
              run: |
                  sudo apt-get install libkrb5-dev -y
                  npm install
                  composer install --no-dev
                  npm run release

            - name: WordPress Plugin Deploy
              uses: 10up/action-wordpress-plugin-deploy@master
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SLUG: smartpay
